// SL Package definition for Exceptions
package Exceptions;

define __getattr_sl__(name):
    try:
        return builtins.getattr(builtins, name)
    except builtins.Exception:
        raise builtins.AttributeError("module 'Exceptions' has no attribute '" + name + "'")

define init():
    pass

// --- Built-in Python Exceptions ---
globals()['ArithmeticError'] = builtins.getattr(builtins, 'ArithmeticError')
globals()['AssertionError'] = builtins.getattr(builtins, 'AssertionError')
globals()['AttributeError'] = builtins.getattr(builtins, 'AttributeError')
globals()['BaseException'] = builtins.getattr(builtins, 'BaseException')
globals()['BaseExceptionGroup'] = builtins.getattr(builtins, 'BaseExceptionGroup')
globals()['BlockingIOError'] = builtins.getattr(builtins, 'BlockingIOError')
globals()['BrokenPipeError'] = builtins.getattr(builtins, 'BrokenPipeError')
globals()['BufferError'] = builtins.getattr(builtins, 'BufferError')
globals()['BytesWarning'] = builtins.getattr(builtins, 'BytesWarning')
globals()['ChildProcessError'] = builtins.getattr(builtins, 'ChildProcessError')
globals()['ConnectionAbortedError'] = builtins.getattr(builtins, 'ConnectionAbortedError')
globals()['ConnectionError'] = builtins.getattr(builtins, 'ConnectionError')
globals()['ConnectionRefusedError'] = builtins.getattr(builtins, 'ConnectionRefusedError')
globals()['ConnectionResetError'] = builtins.getattr(builtins, 'ConnectionResetError')
globals()['DeprecationWarning'] = builtins.getattr(builtins, 'DeprecationWarning')
globals()['EOFError'] = builtins.getattr(builtins, 'EOFError')
globals()['EncodingWarning'] = builtins.getattr(builtins, 'EncodingWarning')
globals()['EnvironmentError'] = builtins.getattr(builtins, 'EnvironmentError')
globals()['Exception'] = builtins.getattr(builtins, 'Exception')
globals()['ExceptionGroup'] = builtins.getattr(builtins, 'ExceptionGroup')
globals()['FileExistsError'] = builtins.getattr(builtins, 'FileExistsError')
globals()['FileNotFoundError'] = builtins.getattr(builtins, 'FileNotFoundError')
globals()['FloatingPointError'] = builtins.getattr(builtins, 'FloatingPointError')
globals()['FutureWarning'] = builtins.getattr(builtins, 'FutureWarning')
globals()['GeneratorExit'] = builtins.getattr(builtins, 'GeneratorExit')
globals()['IOError'] = builtins.getattr(builtins, 'IOError')
globals()['ImportError'] = builtins.getattr(builtins, 'ImportError')
globals()['ImportWarning'] = builtins.getattr(builtins, 'ImportWarning')
globals()['IndentationError'] = builtins.getattr(builtins, 'IndentationError')
globals()['IndexError'] = builtins.getattr(builtins, 'IndexError')
globals()['InterruptedError'] = builtins.getattr(builtins, 'InterruptedError')
globals()['IsADirectoryError'] = builtins.getattr(builtins, 'IsADirectoryError')
globals()['KeyError'] = builtins.getattr(builtins, 'KeyError')
globals()['KeyboardInterrupt'] = builtins.getattr(builtins, 'KeyboardInterrupt')
globals()['LookupError'] = builtins.getattr(builtins, 'LookupError')
globals()['MemoryError'] = builtins.getattr(builtins, 'MemoryError')
globals()['ModuleNotFoundError'] = builtins.getattr(builtins, 'ModuleNotFoundError')
globals()['NameError'] = builtins.getattr(builtins, 'NameError')
globals()['NotADirectoryError'] = builtins.getattr(builtins, 'NotADirectoryError')
globals()['NotImplementedError'] = builtins.getattr(builtins, 'NotImplementedError')
globals()['OSError'] = builtins.getattr(builtins, 'OSError')
globals()['OverflowError'] = builtins.getattr(builtins, 'OverflowError')
globals()['PendingDeprecationWarning'] = builtins.getattr(builtins, 'PendingDeprecationWarning')
globals()['PermissionError'] = builtins.getattr(builtins, 'PermissionError')
globals()['ProcessLookupError'] = builtins.getattr(builtins, 'ProcessLookupError')
globals()['PythonFinalizationError'] = builtins.getattr(builtins, 'PythonFinalizationError')
globals()['RecursionError'] = builtins.getattr(builtins, 'RecursionError')
globals()['ReferenceError'] = builtins.getattr(builtins, 'ReferenceError')
globals()['ResourceWarning'] = builtins.getattr(builtins, 'ResourceWarning')
globals()['RuntimeError'] = builtins.getattr(builtins, 'RuntimeError')
globals()['RuntimeWarning'] = builtins.getattr(builtins, 'RuntimeWarning')
globals()['StopAsyncIteration'] = builtins.getattr(builtins, 'StopAsyncIteration')
globals()['StopIteration'] = builtins.getattr(builtins, 'StopIteration')
globals()['SyntaxError'] = builtins.getattr(builtins, 'SyntaxError')
globals()['SyntaxWarning'] = builtins.getattr(builtins, 'SyntaxWarning')
globals()['SystemError'] = builtins.getattr(builtins, 'SystemError')
globals()['SystemExit'] = builtins.getattr(builtins, 'SystemExit')
globals()['TabError'] = builtins.getattr(builtins, 'TabError')
globals()['TimeoutError'] = builtins.getattr(builtins, 'TimeoutError')
globals()['TypeError'] = builtins.getattr(builtins, 'TypeError')
globals()['UnboundLocalError'] = builtins.getattr(builtins, 'UnboundLocalError')
globals()['UnicodeDecodeError'] = builtins.getattr(builtins, 'UnicodeDecodeError')
globals()['UnicodeEncodeError'] = builtins.getattr(builtins, 'UnicodeEncodeError')
globals()['UnicodeError'] = builtins.getattr(builtins, 'UnicodeError')
globals()['UnicodeTranslateError'] = builtins.getattr(builtins, 'UnicodeTranslateError')
globals()['UnicodeWarning'] = builtins.getattr(builtins, 'UnicodeWarning')
globals()['UserWarning'] = builtins.getattr(builtins, 'UserWarning')
globals()['ValueError'] = builtins.getattr(builtins, 'ValueError')
globals()['Warning'] = builtins.getattr(builtins, 'Warning')
globals()['WindowsError'] = builtins.getattr(builtins, 'WindowsError')
globals()['ZeroDivisionError'] = builtins.getattr(builtins, 'ZeroDivisionError')
globals()['_IncompleteInputError'] = builtins.getattr(builtins, '_IncompleteInputError')